### ISSUE TITLE
Extração pra SQL

### ISSUE THREAD

**Issue by DouglasEleuterio** [mateusccoelho/aws_etl_dados_publicos_cnpj#1]
Olá @mateusccoelho sou Dev e gostaria de construir uma solução gratuita pra o público em geral consultar dados das empresas com dados sempre atualizados.
O meu empecilho é na extração dos dados, pois não dominino o assunto.
Vi sei git lá do dados.giv.br 
Você poderia me orientar sobre como proceder para extrair os dados para migração para base da dados SQL utilizando sua ferramenta?

**Comment by mateusccoelho** [comment]
Oi Douglas, tudo bem? Imagino que você queira armazenar os dados em um banco de dados PostgreSQL ou MySQL usando o AWS RDS. Eu não entendo muito desse serviço e nunca o utilizei, mas sugiro que você olhe as ferramentas de migração/ingestão de dados do RDS. Com certeza deve ter uma forma de mover os dados de um bucket S3 para o banco. 

Então, sugiro utilizar o ETL que desenvolvi e adicionar uma etapa no final que seria a ingestão no RDS. Porém, essa estratégia envolve alguns detalhes que não sei como resolver, por exemplo:

- Todo mês o governo gera uma nova "fotografia" dos dados do CNPJ. Com certeza, de um mês para o outro a maioria dos dados não deve mudar. Então você teria duas opções: remover a tabela do mês anterior e criar uma nova com a nova fotografia ou detectar apenas as linhas que foram alteradas e fazer um update. 

Deixando o RDS de lado, outra opção seria criar um cluster do Amazon Redshift. Também nunca o utilizei, mas sei que é um serviço de data warehouse com bom desempenho e facilmente escalável. E a carga de dados nele a partir do S3 é bem simples, algo como alguns comandos SQL.

Recomendo dar uma olhada nesses dois serviços. Infelizmente não consigo te ajudar muito na prática porque estou começando agora meus estudos de engenheria de dados.
